"""Initial Migration

Revision ID: 9af7105c4d9f
Revises: 
Create Date: 2024-10-12 20:29:35.423733

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '9af7105c4d9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
