"""Initial Checkin

Revision ID: bc599acc85fa
Revises: 
Create Date: 2024-10-14 09:55:23.346864

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc599acc85fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('first_name', sa.VARCHAR(length=2000), nullable=False),
                    sa.Column('last_name', sa.VARCHAR(length=2000), nullable=False),
                    sa.Column('disabled', sa.VARCHAR(length=1), server_default='N', nullable=False),
                    sa.Column('creation_date', postgresql.TIMESTAMP(), nullable=False),
                    sa.Column('update_date', postgresql.TIMESTAMP(), nullable=False),
                    sa.Column('created_by', sa.BIGINT(), nullable=False),
                    sa.Column('updated_by', sa.BIGINT(), nullable=False),
                    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['updated_by'], ['user.user_id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    op.create_table('activity',
                    sa.Column('activity_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('activity_desc', sa.VARCHAR(length=2000), nullable=False),
                    sa.Column('disabled', sa.VARCHAR(length=1), server_default='N', nullable=False),
                    sa.Column('creation_date', postgresql.TIMESTAMP(), nullable=False),
                    sa.Column('update_date', postgresql.TIMESTAMP(), nullable=False),
                    sa.Column('created_by', sa.BIGINT(), nullable=False),
                    sa.Column('updated_by', sa.BIGINT(), nullable=False),
                    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['updated_by'], ['user.user_id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('activity_id')
                    )
    op.create_table('workout',
                    sa.Column('workout_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('activity_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('start_time', postgresql.TIMESTAMP(), nullable=False),
                    sa.Column('end_time', postgresql.TIMESTAMP(), nullable=True),
                    sa.Column('creation_date', postgresql.TIMESTAMP(), nullable=False),
                    sa.Column('update_date', postgresql.TIMESTAMP(), nullable=False),
                    sa.Column('created_by', sa.BIGINT(), nullable=False),
                    sa.Column('updated_by', sa.BIGINT(), nullable=False),
                    sa.ForeignKeyConstraint(['activity_id'], ['activity.activity_id'], ),
                    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['updated_by'], ['user.user_id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
                    sa.PrimaryKeyConstraint('workout_id')
                    )
    op.create_table('workoutdetail',
                    sa.Column('workout_detail_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('workout_id', sa.Integer(), nullable=False),
                    sa.Column('rep_count', sa.Integer(), nullable=True),
                    sa.Column('weight', sa.Float(), nullable=True),
                    sa.Column('start_time', postgresql.TIMESTAMP(), nullable=True),
                    sa.Column('end_time', postgresql.TIMESTAMP(), nullable=True),
                    sa.Column('creation_date', postgresql.TIMESTAMP(), nullable=False),
                    sa.Column('update_date', postgresql.TIMESTAMP(), nullable=False),
                    sa.Column('created_by', sa.BIGINT(), nullable=False),
                    sa.Column('updated_by', sa.BIGINT(), nullable=False),
                    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['updated_by'], ['user.user_id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['workout_id'], ['workout.workout_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('workout_detail_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workoutdetail')
    op.drop_table('workout')
    op.drop_table('activity')
    op.drop_table('user')
    # ### end Alembic commands ###
