"""Add dictionary functions

Revision ID: c36290677d6a
Revises: 9af7105c4d9f
Create Date: 2024-10-12 22:21:42.476450

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c36290677d6a'
down_revision: Union[str, None] = '9af7105c4d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
